# Site settings
author: Fahima Hyder
title: My journey to becoming a Data Scientist
header-img: img/home-bg.png
email: hyderfahima@gmail.com
copyright_name: Fahima Hyder
description: > # this means to ignore newlines until "baseurl:"
  a study in studying
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  FHyder

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
